robofont-mechanic/mechanic-2-server

_data/blueZoneEditor.yml
My mistake, bad URL for the icon!
=> Fixes the metadata for the Blue Zone Editor icon url

_data/checkParallelTool.yml
=> Added new extension

_data/EditThatNextMaster.yml
=> EditThatNext scripts packaged as RoFoExto.

_data/booster.yml, _data/pasteGlyph.yml
Add two extensions from Type Supply LLC.
=> Add Booster and Paste Glyph.

_data/Theme-Manager.yml
Added Theme-Manager extension.
=> Added Theme-Manager.yml

_data/markyMark.yml, _data/spaceCase.yml
I made an extension. I think I'm doing this right.
=> new extension

_data/addSegmentGuidelines.yml
I hope all is good!
Have a nice day, Jan
=> yml for Add segment guideline extension

_data/ScaleAbsolutely.yml
I hope it's fine :) Cheers, Jan
=> yml for extension that allows to scale in points, not percent

_data/symmetricRoundShapeDrawingTool.yml
A tool for drawing symmetric round shapes in RoboFont.
=> add symmetricRoundShapeDrawingTool

_data/booster.yml, _data/popUpTools.yml
- Remove Booster because no one uses it.
- Add Pop Up Tools because I use it.
=> Type Supply Tool Dept. 2020-05-28

_data/glyphWalker.yml
This is an old version here. Somehow I wasn't aware that it existed already, when I uploaded the new version.
=> Delete (old) glyphWalker.yml

_data/layerThief.yml
=> Add Layer Thief yml

_data/InspectorMini.yml, _data/ScriptLauncher.yml
Hi. Here are two new RoboFont extensions: ScriptLauncher and InspectorMini.
=> Adding ScriptLauncher and InspectorMini

_data/guideTool.yml, _data/merzPlayground.yml
Please let me know if I did anything wrong.
=> Add Merz Playground and Guide Tool.

_data/delorean:InterpolationPreview.yml
update repo and ext path so delorean has its own repo : )
=> update repo and ext path so delorean has its own repo : )

_data/CAMSimulator.yml
=> add CAM Simulator

_data/similarity.yml, _data/superpolatorRemote.yml, _data/symmetricRoundShapeDrawingTool.yml
A fun extension that may not be entirely done but it is done enough I think. 
Also removes SuperpolatorRemote and SymmetricShape extensions.
=> Add LTR Similarity

_data/CodeThemeManager.yml, _data/kernTool4.yml
Сode theme manager for Robofont 4 Scripting Window.
=> new extension CodeThemeManager

_data/CodeThemeManager.yml, _data/ScriptsBoard.yml, _data/kernTool4.yml
New ScriptsBoard extension. Adds a panel to the Inspector to quickly launch your favorite scripts
=> ScriptsBoard

_data/Version-Spy.yml
Adding the Version Spy extension https://github.com/ohnotypeco/Version-Spy-Ext
=> Adding Version Spy

_data/longboard.yml
Nice Designspace Previews For The Robofonts!
=> Longboard 1.3.2
